configs:
- id: alert_pf_prodops
  config:
    name: production_ops
    template: alert_pf_prodops.json
    skip: false
  type:
    api: alerting-profile
- id: alert_pf_devops
  config:
    name: devops
    template: alert_pf_devops.json
    skip: false
  type:
    api: alerting-profile
- id: alert_pf_sre
  config:
    name: sre
    template: alert_pf_sre.json
    skip: false
  type:
    api: alerting-profile
